### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirMonitor#1]
Items as they come up:

-----
_TODO:_

- [x] future bug

----
_Items finished on 2022-01-12_

- [x] make sure to assign the result of `setIfNull()`

----
_Items finished on 2021-11-18_

- [x] need to export `%>%`
- [x] `monitor_timeseriesPlot(addAQI = ...)` should default to `FALSE` 
- [x] update `monitor_filterData()` to match updated **MazamaTimeSeries**

----
_Items finished on 2021-11-16_

- [x] have higher values plotted on top in leaflet map
- [x] reorder `year` and `parameterCode` arguments in `epa_aqs_loadAnnual()`
- [x] have `monitor_filter()` be an alias for `monitor_filterMeta()` and include a new `monitor_filterData()` which will seldom be used

----
_Items finished on 2021-10-18_

- [x] use all caps for units
