### ISSUE TITLE
TODO checklist for 2022

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirMonitor#5]
Items as they come up:

-----
_TODO:_

- [ ] Rebuild example datasets from V2 archives built with `fullAQSID`
- [ ] Update `vignettes/AirMonitor.Rmd`
- [ ] Update and move back articles from `local_articles/`
- [ ] Add `monitor_slice()` to select based on row indices in the `meta` table. (7/13)
- [ ] `monitor_load()` only has data up to the end of `loadDaily()` as opposed to the end of `loadLatest()`. (8/23)
- [ ] monitor validation currently requires `fullAQSID` which is not available for WRCC data. (9/06)
- [ ] `.determineTimezone()` fails when multiple monitors are present (4/18)
```
> monitor %>% monitor_filterDatetime(starttime, endtime)
Error in .determineTimezone(mts, startdate, timezone, verbose = TRUE) :
timezone '' is not a valid Olson timezone
```

----
_Items finished by 2022-02-24_

- [x] Add `QC_removeSuspectData = TRUE` as argument to `airsis_load~()`and `wrcc_load~()` functions. (9/23)

----
_Items finished on 2022-08-10_
- [x] Update `monitor_toPWFSLSmoke()` to use `fullAQSID`
- [x] Update `monitor_fromPWFSLSmoke()` to use `fullAQSID`
- [x] Time filtering functions should allow the start or end to be `NULL`. In this case, just use the beginning or end of the time series. (08/08)

----
_Items finished on 2022-06-10_

- [x] Add TODO checklist (6/10)
