### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirMonitor#6]
Items as they come up:

-----
_TODO:_

_New in 2026_

- [ ] Add `monitor_dailyMean()` from iwfaqrp_small_projects repo (3/23/26)
- [ ] Use Amazon Route 53 to track data downloads (6/10/26)

_New in 2025_

- [ ] `Error in monitor_leaflet(., slice = 690) :  improper use of slice parameter` (5/29/25)
- [ ] `monitor_aqcTable()` fails if any monitor is missing `locationName` (7/18/25)
- [ ] allow `aqiCategories()` and `aqiColors()` to accept a matrix as input, _e.g._ a "dataBrick", and return a matrix as output (10/31/25)
- [ ] update NowCast article to reflect missing value logic that now matches AirNow. (10/31/25)

_New in 2024_

- [ ] all `monitor_()` functions that return _monitor_ objects should test with `monitor_isEmpty()` as the first step and, if empty, return the unmodified _monitor_. This will prevent errors from occurring in the middle of a recipe. (2/29/24)
- [ ] Rebuild example datasets from V2 archives built with `fullAQSID`
- [ ] Update `vignettes/AirMonitor.Rmd`
- [ ] Update and move back articles from `local_articles/`
- [ ] `monitor_load()` only has data up to the end of `loadDaily()` as opposed to the end of `loadLatest()`. (8/23/23)
- [ ] monitor validation currently requires `fullAQSID` which is not available for WRCC data. (9/06/23)
- [ ] `monitor_getCurrentStatus()` should use `monitor_filterDatetime()` with `ceilingEnd = TRUE` once **MazamaTimeSeries** has been updated with the associated fix. (6/30/23)
- [ ] Update PM2.5 NAAQS to match air-monitor-plots.js. (8/5/24)
- [ ] Levi Stanton Slack comment about NAAQS in `.assignBreakpointsTable()`. (8/07/2024)

_version 0.5.x_

- [ ] In `monitor_aqi()` figure out whether NowCast should be applied to non-PM2.5 data. (12/03/2024)

----
_Items finished by 2024-09-26_

- [x] Revisit NowCast calculation (8/10/23)
>I was reading through your NowCast code and saw that you don't calculate NowCast if the current hour is missing. I know you note that it conflicts with the algorithm on the airnowtech blog, but you also cite a wikipedia article that says that's how it's done for AirNow. Problem is, that's not how it's done for AirNow.

----
_Items finished by 2024-02-09_

- [x] Add `monitor_slice()` to select based on row indices in the `meta` table. (7/13/23)
- [x] Add `monitor_pull()` to do `monitor_getMeta() %>% dplyr::pull()` (1/16/24)
- [x] Add `aqiCategories()` to return 1:6 similar to `aqiColors()` (1/25/24)
- [x] Add `US_AQI$breaks_PM2.5_2024` with updated breaks. (2/8/24)
- [x] Add `monitor_toAqcTable()` to create a table with category columns, ddID rows and a count of days in a category for each cell. (2/8/24)
- [x] Add `monitor_setTimeAxis()` for cases where you want to extend a time series to mach other, longer time series. (9/05/23)

----
_Items finished by 2023-08-25_

- [x] Added `@aliases <package>-package` after `@docType package` to satisfy CRAN. (8/23)
- [x] Updated `monitor_load~()` functions to always use most recent data at a location. (8/24)
